### PR TITLE
fix weekday of birthdays

### LINKED ISSUE #230: Wrong weekday for birthdays
View competitor "Linus Fresz" in admin/user-mode at the competitors list for German Nationals 2016 for this issue.
His birthday is at the Sunday of the competition (09.10), cubecomp says "Birthday on Monday". I guess this happens from that the competition starts on Friday, but somehow cubecomp starts counting the date from Saturday, so the date gets shifted to one day later.

### PR DESCRIPTION
**Pull request by Laura-O**
This should fix #230.

This fix is not perfect as it ignores the possibility that a competition is taking place in two different years.
However, it is unlikely that a competition spans over two years, so in general it should be working as expected.
Feel free to ignore this PR if it doesn't meet your quality standards. :-)

### CODE REVIEW

**Comment by fw42** [comment]
Thanks for making a PR. The idea makes sense to me (and I think for now it's acceptable that this is wrong if the competition falls on the last day of the year and similar edge cases).

I think we can make it a bit cleaner by moving this logic from the view into the model.

The `Competitor` class could have an instance method that does this, something like:
```ruby
def birthday_in_competition_year
  birthday.change(:year => current_competition.days.first.date.year)
end
```
and then the view could just call that new method.

Could you also add a unit test for this? (in `test/models/competitor_test.rb`)

**Comment by fw42** [comment]
Actually, I think we can make it even easier, by reusing the existing logic. Take a look at [this](https://github.com/fw42/cubecomp/blob/30ff2a6f4d6263489b04b37359f52d0fe32a23e3/app/models/competitor.rb#L105-L107):
```ruby
def birthday_on_competition?
  days.any?{ |day| birthday_on?(day.date) }
end
```
which checks if the competitor has a birthday on one of the competition days (and returns true if so and false otherwise). We can reuse the same logic by changing [any?](http://ruby-doc.org/core-2.2.3/Enumerable.html#method-i-any-3F) to [detect](http://ruby-doc.org/core-2.2.3/Enumerable.html#method-i-detect) (which would make it return the competition day that is the competitors birthday, which means this will also automatically work for your edge-case):
```ruby
def birthday_on_competition
  days.detect{ |day| birthday_on?(day.date) }
end

def birthday_on_competition?
  !!birthday_on_competition
end
```
or something like that.

Does that make sense?

**Comment by Laura-O** [comment]
Changed the files now and everything is working as expected.

I am a bit unsure about the unit test - is this enough or do we need to test more?

File: test/models/competitor_test.rb [hunk 1]
```diff
@@ -244,10 +244,10 @@ class CompetitorTest < ActiveSupport::TestCase
     end
   end
 
-  test '#birthday_on?' do
+  test '#birthday_on_competition?' do
```
Comment (fw42) [inline test/models/competitor_test.rb]: instead of changing the existing test, can you just add a new one (and leave the old one as it was)?

**Comment by fw42** [comment]
One comment about the test. The rest looks good.

Thanks Laura! 👍

**Comment by Laura-O** [comment]
Awesome!
Added back the old test and I think I understood why that makes sense! 😄
